### ISSUE TITLE
On v8, facets are split on space

### ISSUE THREAD

**Issue by TimGeyssens** [designagencyuk/DesignAgency.BoboFacets#10]
seems if you have a value like

"this is one"

the facets will be

this
one

**Comment by TomSteer** [comment]
I've just tried this on the example project and it seems to index the value correctly (as "this is one" and not separate facets).

It's set to not analyze the facet field (https://github.com/designagencyuk/DesignAgency.BoboFacets/blob/v8/development/DesignAgency.BoboFacets/Models/FacetField.cs#L113), are you using a custom FacetField where you override this method? 

The example project is an early version of V8 so not sure if something has changed in a later version.

**Comment by TimGeyssens** [comment]
yeah the index seems correct... but seems to happen in the ConvertToFacetGroups ... number of groups is correct but all values are split and also excluding stopwords ... any ideas? Thanks

**Comment by TomSteer** [comment]
What type of property is the facet and how is the facet field configured?

**Comment by TimGeyssens** [comment]
think I found it, the facet field wasn't set to Field.Index.NOT_ANALYZED
