### ISSUE TITLE
Umbraco 8

### ISSUE THREAD

**Issue by Jogai** [designagencyuk/DesignAgency.BoboFacets#11]
When upgrading from Umbraco 7 its best to go to 8.5.5. However for the bobofacets 8.6.0 is needed. Could you publish a package that lowers the Umbraco Requirement a tiny bit?

We're in the situation that we're trying to upgrade to 8.5.5 as an intermediate step. If that works (including the bobostuff) we can upgrade test/production and take the next step to the latest 8.x.

**Comment by TomSteer** [comment]
Hi @Jogai I've released 2.0.1-beta that lowers the min Umbraco version to 8.5.1

**Comment by Jogai** [comment]
That's awesome, thanks!
